import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  Header  from "@/shared/ui/Header"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App autores",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const routes = [
    { name: "Lista de autores", path: "/authors" },
    { name: "Crear autor", path: "/crear/new" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header
          routes={routes}
        />
        {children}
      </body>
    </html>
  );
}
